
ARDUINO_ROOT = $(HOME)/projects/esp/esp-arduino/portable
CHIP = esp8266
BOARD = nodemcuv2
FLASH_DEF = 4M1M
SKETCH = thermostat.ino
UPLOADPORT = /dev/ttyAMA0

include $(HOME)/projects/esp/makeEspArduino/makeEspArduino.mk
